# Generated by Django 5.0.14 on 2025-06-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ელ_ფოსტა',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True, verbose_name='ელ. ფოსტა'),
            preserve_default=False,
        ),
    ]
