# Generated by Django 5.0.14 on 2025-06-15 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('სახელი', models.CharField(max_length=255, unique=True, verbose_name='ავტორის სახელი')),
                ('აღწერა', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
            ],
            options={
                'verbose_name': 'ავტორი',
                'verbose_name_plural': 'ავტორები',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('სახელი', models.CharField(max_length=50, unique=True, verbose_name='მდგომარეობის სახელი')),
                ('აღწერა', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
            ],
            options={
                'verbose_name': 'მდგომარეობა',
                'verbose_name_plural': 'მდგომარეობები',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('სახელი', models.CharField(max_length=100, unique=True, verbose_name='ჟანრის სახელი')),
            ],
            options={
                'verbose_name': 'ჟანრი',
                'verbose_name_plural': 'ჟანრები',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('სათაური', models.CharField(max_length=255, verbose_name='სათაური')),
                ('აღწერა', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
                ('სურათი', models.ImageField(blank=True, null=True, upload_to='წიგნის_პოსტერები/', verbose_name='სურათი')),
                ('ხელმისაწვდომია', models.BooleanField(default=True, verbose_name='ხელმისაწვდომია')),
                ('მიღების_ლოკაციის_დეტალები', models.TextField(blank=True, help_text='კონკრეტული დეტალები ამ წიგნის ასაღებად.', null=True, verbose_name='მიღების ლოკაციის დეტალები')),
                ('შექმნის_თარიღი', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('განახლების_თარიღი', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('ავტორი', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='წიგნები', to='books.author', verbose_name='ავტორი')),
                ('მფლობელი', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='შეთავაზებული_წიგნები', to=settings.AUTH_USER_MODEL, verbose_name='მფლობელი')),
                ('მდგომარეობა', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='წიგნები', to='books.condition', verbose_name='მდგომარეობა')),
                ('ჟანრი', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='წიგნები', to='books.genre', verbose_name='ჟანრი')),
            ],
            options={
                'verbose_name': 'წიგნი',
                'verbose_name_plural': 'წიგნები',
                'ordering': ['-შექმნის_თარიღი'],
            },
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('სტატუსი', models.CharField(choices=[('მოლოდინში', 'მოლოდინში'), ('მიღებულია', 'მიღებულია'), ('უარყოფილია', 'უარყოფილია')], default='მოლოდინში', max_length=20, verbose_name='სტატუსი')),
                ('შეტყობინება', models.TextField(blank=True, null=True, verbose_name='შეტყობინება')),
                ('შექმნის_თარიღი', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('განახლების_თარიღი', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('დაინტერესებული_მომხმარებელი', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='მოთხოვნილი_წიგნები', to=settings.AUTH_USER_MODEL, verbose_name='დაინტერესებული მომხმარებელი')),
                ('წიგნი', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='მოთხოვნები', to='books.book', verbose_name='წიგნი')),
            ],
            options={
                'verbose_name': 'წიგნის მოთხოვნა',
                'verbose_name_plural': 'წიგნის მოთხოვნები',
                'unique_together': {('წიგნი', 'დაინტერესებული_მომხმარებელი')},
            },
        ),
    ]
